[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
# Use clang instead of GCC / G++
# See more about the bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y wget gnupg software-properties-common",
    "wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /usr/share/keyrings/llvm.gpg",
    "echo \"deb [signed-by=/usr/share/keyrings/llvm.gpg] http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm main\" > /etc/apt/sources.list.d/llvm.list",
    "apt-get update",
    "apt-get install -y clang-18 libclang-18-dev",
    "update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100",
    "update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100",
]

[target.x86_64-unknown-linux-gnu.env]
passthrough = [
    "CC=clang",
    "CXX=clang++",
    "AWS_LC_SYS_CC=clang",
]

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:main"
pre-build = [
    "apt-get update",
    "apt-get install -y clang nasm mingw-w64 mingw-w64-x86-64-dev zlib1g-dev liblz4-dev libzstd-dev libsnappy-dev"
]

[target.x86_64-pc-windows-gnu.env]
passthrough = ["BINDGEN_EXTRA_CLANG_ARGS", "BINDGEN_EXTRA_CLANG_ARGS='--target=x86_64-w64-mingw32 -I/usr/x86_64-w64-mingw32/include'"]